# Generated by Django 5.1.4 on 2025-01-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='author',
            new_name='publication',
        ),
    ]
