# Generated by Django 5.1.7 on 2025-03-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentfeedback',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='TeacherFeedback',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='teacher',
        ),
    ]
