# Generated by Django 5.1.4 on 2025-01-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_attendancereport_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AttendanceReport",
        ),
    ]
