# Generated by Django 5.1.4 on 2025-01-15 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_delete_attendancereport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassRoutine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.subject"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.teacher"
                    ),
                ),
            ],
        ),
    ]
