# Generated by Django 5.1.7 on 2025-03-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coursetracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Feedback', 'verbose_name_plural': 'Student Feedbacks'},
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='subject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='teacher',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.staff'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentfeedback',
            unique_together={('student', 'subject', 'teacher')},
        ),
    ]
