# Generated by Django 5.1.4 on 2025-01-10 06:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('issued_by', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='character_certificates/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_certificates', to='app.student')),
            ],
            options={
                'verbose_name': 'Character Certificate',
                'verbose_name_plural': 'Character Certificates',
            },
        ),
    ]
