# Generated by Django 5.1.5 on 2025-01-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_academicyear_course_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="description",
        ),
        migrations.AddField(
            model_name="subject",
            name="duration",
            field=models.PositiveIntegerField(
                default="1",
                help_text="For semester-based courses, specify the semester number. For year-based courses, specify the year.",
            ),
            preserve_default=False,
        ),
    ]
