# Generated by Django 5.1.4 on 2025-01-08 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_level_alter_staff_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='exam_date',
            field=models.DateField(help_text='Date of the examination'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'Excellent'), ('A', 'Very Good'), ('B', 'Good'), ('C', 'Average'), ('D', 'Below Average'), ('F', 'Fail')], help_text='Grade assigned based on marks', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='marks_obtained',
            field=models.PositiveIntegerField(help_text='Marks obtained by the student', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='total_marks',
            field=models.PositiveIntegerField(help_text='Total marks for the subject', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
