# Generated by Django 5.1.4 on 2025-01-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_charactercertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercertificate',
            name='student',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CharacterCertificate',
        ),
    ]
