# Generated by Django 5.1.7 on 2025-03-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_studentfeedback_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentfeedback',
            unique_together={('student', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='subject',
        ),
    ]
