# Generated by Django 5.1.4 on 2025-01-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_complaint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="academic_year",
        ),
    ]
