# Generated by Django 5.1.4 on 2025-01-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_marksheet_subj_result'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marksheet',
            unique_together={('student', 'course')},
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='subject',
        ),
    ]
