# Generated by Django 5.1.4 on 2025-01-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_staff_user_student_user_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
