# Generated by Django 5.1.4 on 2025-01-10 06:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_charactercertificate_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='obtained_marks',
            field=models.PositiveIntegerField(default=Decimal('0.00'), validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='total_marks',
            field=models.PositiveIntegerField(default=Decimal('0.00'), validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
