# Generated by Django 5.1.4 on 2025-01-10 06:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_marksheet_grade_alter_marksheet_obtained_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmark',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
    ]
