# Generated by Django 5.1.4 on 2025-01-15 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_complaint_academic_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("notes", models.FileField(upload_to="media/notes")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.subject"
                    ),
                ),
            ],
        ),
    ]
