# Generated by Django 5.1.4 on 2025-01-10 06:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_subjectmark_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, default=Decimal('0.00'), null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
