# Generated by Django 5.1.4 on 2025-01-16 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="active_status",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="active_status",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="active_status",
            new_name="is_active",
        ),
    ]
