# Generated by Django 5.1.4 on 2025-01-08 08:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_marksheet_marks_obtained_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmark',
            name='marks_obtained',
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='obtained_practical_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='obtained_theory_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='total_practical_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='total_theory_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
    ]
