# Generated by Django 5.1.5 on 2025-01-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_leavereportstudent_leave_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.RemoveField(
            model_name="student",
            name="username",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="password",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="username",
        ),
    ]
