# Generated by Django 5.1.4 on 2025-01-08 08:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_subjectmark_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmark',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
