# Generated by Django 5.1.5 on 2025-01-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_student_password_remove_student_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackstudent",
            name="feedback_reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
