# Generated by Django 5.1.4 on 2025-01-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_staff_group_remove_student_group_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="group",
            field=models.ManyToManyField(blank=True, to="auth.group"),
        ),
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ManyToManyField(blank=True, to="auth.group"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="group",
            field=models.ManyToManyField(blank=True, to="auth.group"),
        ),
    ]
