# Generated by Django 5.1.4 on 2025-01-08 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_marksheet_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='total_marks',
            field=models.PositiveIntegerField(help_text='Total marks for the course', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
