# Generated by Django 5.1.5 on 2025-01-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_feedbackstudent_feedback_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedbackteacher",
            old_name="staff_id",
            new_name="teacher_id",
        ),
        migrations.AlterField(
            model_name="feedbackteacher",
            name="feedback_reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
