# Generated by Django 5.1.4 on 2025-01-08 09:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_marksheet_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='obtained_marks',
            field=models.PositiveIntegerField(default=Decimal('0.00'), editable=False, help_text='Total marks obtained by the student', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='total_marks',
            field=models.PositiveIntegerField(default=Decimal('0.00'), editable=False, help_text='Total marks for the course', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
