# Generated by Django 5.1.5 on 2025-01-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_rename_staff_id_feedbackteacher_teacher_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="academic_year",
            new_name="academic_year_id",
        ),
    ]
