# Generated by Django 5.1.4 on 2025-01-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_marksheet_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'Outstanding'), ('A', 'Excellent'), ('B+', 'Very Good'), ('B', 'Good'), ('C+', 'Above Average'), ('C', 'Average'), ('D', 'Below Average'), ('E', 'Fail')], help_text='Grade assigned based on marks', max_length=2, null=True),
        ),
    ]
