# Generated by Django 5.1.4 on 2025-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_staff_group_alter_student_group_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='group',
        ),
        migrations.AddField(
            model_name='staff',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
    ]
